### ISSUE TITLE
这个项目还在维护吗(

### ISSUE THREAD

**Issue by rickly233** [Lanly109/CodingReminder#1]
如题

**Comment by Lanly109** [comment]
当然，有更换获取比赛数据源的计划，还没开工（

**Comment by rickly233** [comment]
有考虑写成nonebot2的插件吗,,,现在nonebot2适配不了nonebot1的插件了(

**Comment by Lanly109** [comment]
没有打算诶，我没用过`nonebot2`，不太了解`nonebot2`的结构（也测试不了），一直都是用基于`nonebot1`的`hoshino`。
不过两者应该只是触发器不太一样，重写下服务端代码应该就可以？

**Comment by rickly233** [comment]
好的好的,nonebot2没有类似的算法竞赛提醒插件,然后在github找到了这个项目,以后我试着改一下吧.
